### ISSUE TITLE
Cantaloupe not running

### ISSUE THREAD

**Issue by nvanderperren** [VlaamseKunstcollectie/Imagehub-Box#8]
I get a 404 when I go to http://192.168.2.152:8080/cantaloupe/. When I surf to cantaloupe.box I get a *Welcome to nginx!* screen. http://cantaloupe.box/cantaloupe/admin  returns a 404.

I know for sure that tomcat is running:
- `service tomcat8 status` returns active
- going to http://192.168.2.152:8080/ gives me the *it works*-message.

I can't access 192.168.2.152:8080/manager/html with username and password in tomcat.yml. I always get a `401 Unauthorized`.

**Edit:** `ls /opt` doesn't show me a cantaloupe folder (although cantaloupe.yml indicates that cantaloupe should be installed in /opt). There is also no `.war` file in /var/lib/tomcat8/webapps.

The *welcome to nginx!* is probably related to the nginx.yml configuration:

```yaml
- listen: "80"
    server_name: "cantaloupe.box"
    root: "/vagrant/project-cantaloupe"
    index: "index.php index.html index.htm"
    access_log: "/var/log/nginx/cantaloupe_access.log"
    error_log: "/var/log/nginx/cantaloupe_error.log"
    extra_parameters: |
      location / {
        proxy_pass         http://127.0.0.1:8080;
        proxy_redirect     off;

        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
      }
```

There is no project-cantaloupe in the /vagrant folder. Do I need to create a project-cantaloupe folder in the vagrant_synced_folder?
